
# Numpy Part 2

In [1]:
import numpy as np

In [10]:
empty = np.empty((2, 3))
print(empty)
print('-----------------------')
print(empty[0])

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [9.34609111e-307 1.42413555e-306 1.78019082e-306]]
-----------------------
[6.23042070e-307 4.67296746e-307 1.69121096e-306]


In [16]:
even = np.arange(0, 20, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
lin = np.linspace(0, 30, num=10)
lin

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [14]:
x = np.arange(11, 25, 2)
x

array([11, 13, 15, 17, 19, 21, 23])

In [35]:
x = np.arange(2, 25, 2,  dtype=np.float64)
x

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [36]:
# sorting an array
x = np.array([1, 2, 10, 3, 0, 4, 5, 6, 7, 8, 9])
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8, 9, 10])
c = np.concatenate((a, b))  # equivalent to np.append(a, b)
c

array([ 1,  2,  3,  4,  5,  4,  5,  6,  7,  8,  9, 10])

In [59]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
y = np.array([[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
# concatenate x and y
z = np.concatenate((x, y), axis=1)
z


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [68]:
# create 3d array
x = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
x
x.shape


(2, 2, 3)

In [77]:
# reshape x
y = x.reshape(4, 3)
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Indexing And Slicing

In [86]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[a  > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [89]:
# use two conditions
a[(a > 2) & (a <10) & (a % 2 == 0)]

array([4, 6, 8])

In [90]:
# use three conditions and filter a
a[(a > 2) & (a <10) & (a % 2 == 0) & (a % 3 == 0)]

array([6])

In [91]:
a[(a > 2) | (a <10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])