# numpy Indexing and Slicing 

In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a[4]

np.int64(5)

In [4]:
b = a.reshape(2, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b[1]

array([4, 5, 6])

---
# Making an array from a data or another array

In [6]:
a = np.arange(0, 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [7]:
len(a)

45

In [8]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([7, 8, 9, 10, 11, 12])
c = np.array([13, 14, 15, 16, 17, 18])
d = np.hstack((a, b, c))
print(d)
e = np.vstack((a, b, c))
e

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

---------
# Matrix or matrices

In [10]:
# create a matrix 2 x 3
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# create a matrix in big dimension
a = np.arange(0, 200, 5).reshape(5, 8)
a

array([[  0,   5,  10,  15,  20,  25,  30,  35],
       [ 40,  45,  50,  55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145, 150, 155],
       [160, 165, 170, 175, 180, 185, 190, 195]])

In [22]:
# slicing of matrix
a[3:5, 2:4]

array([[130, 135],
       [170, 175]])

In [27]:
a.max(), a.min(), sum(a)


(np.int64(195), np.int64(0), array([400, 425, 450, 475, 500, 525, 550, 575]))

In [32]:
a

array([[  0,   5,  10,  15,  20,  25,  30,  35],
       [ 40,  45,  50,  55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145, 150, 155],
       [160, 165, 170, 175, 180, 185, 190, 195]])

In [ ]:
a.max(axis=0), # only for column 

(array([160, 165, 170, 175, 180, 185, 190, 195]),)

In [35]:
a.min(axis=1) # only for row

array([  0,  40,  80, 120, 160])

In [36]:
b = np.arange(0, 20, 2).reshape(5, 2)
b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [39]:
c = b + np.array([2, 2])
c

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [40]:
np.flip(c)

array([[20, 18],
       [16, 14],
       [12, 10],
       [ 8,  6],
       [ 4,  2]])

In [41]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.random.random((3, 3))

array([[0.70404447, 0.05267812, 0.04427017],
       [0.34415598, 0.34383117, 0.98669881],
       [0.97433288, 0.42951926, 0.38538608]])

In [49]:
a = np.array([1, 1 , 1, 2, 3, 4, 5, 6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [53]:
a.reshape(2, 4)

array([[1, 1, 1, 2],
       [3, 4, 5, 6]])

In [54]:
a

array([1, 1, 1, 2, 3, 4, 5, 6])

In [52]:
c = a.ravel()
c

array([1, 1, 1, 2, 3, 4, 5, 6])

In [59]:
a = np.arange(3, 39, 3).reshape(4, 3)

In [60]:
a

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36]])

In [69]:
a.ravel()

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])